/**
 * SARVA TECH — TOKEN DEFINITIONS
 *
 * This is the ONLY file in the project that may contain a literal colour value.
 * Everything downstream is generated or typed from here:
 *
 *   lib/tokens.data.mjs  (this file — raw values)
 *     -> lib/tokens.ts             typed access for TS/TSX
 *     -> styles/tokens.css         generated by scripts/generate-tokens.mjs
 *
 * See CLAUDE.md sections 4.1-4.5.
 */

/** Raw palette. Named by what the colour IS, never by where it is used. */
export const palette = {
  // Night
  deepGreen: '#001D13', // CLAUDE.md 4.1 night surface-base
  deepGreenRaised: '#022C1E', // 4.1 night surface-raised
  deepGreenFrame: '#121F1D', // 4.1 night surface-frame
  mist: '#E8F3EE', // 4.2 night text-primary
  mistMuted: '#8BA099', // 4.2 night text-muted

  // Day
  bone: '#F5F2EC', // 4.1 day surface-base
  boneRaised: '#FFFFFF', // 4.1 day surface-raised
  boneFrame: '#E4E0D7', // 4.1 day surface-frame
  ink: '#08241A', // 4.2 day text-primary
  inkMuted: '#4A5B52', // 4.2 day text-muted

  // Accent — identical in both themes as a FILL. See 4.2.
  amber: '#F59B02', // 4.2 accent
  amberDeep: '#986001', // 4.2 day accent-text (accent is 1.96:1 on bone; unusable as text)
  onAmber: '#0A1410', // 4.2 on-accent

  // Status readout (4.6 / 8). Not specified in CLAUDE.md — added, see report.
  signalGreen: '#3FCF8E', // night status-ok
  signalGreenDeep: '#0C6B45', // day status-ok
  signalRed: '#FF8E7A', // night status-down
  signalRedDeep: '#A32718', // day status-down
};

/**
 * Colour tokens, resolved per theme.
 *
 * Key = Tailwind colour key, so `primary` is used as `text-primary`,
 * `surface-base` as `bg-surface-base`, `line` as `border-line`. The names below
 * map 1:1 onto CLAUDE.md 4.1/4.2 in the way they are written at the call site.
 */
export const colorTokens = {
  // -- 4.1 Surfaces -------------------------------------------------------
  'surface-base': { night: palette.deepGreen, day: palette.bone },
  'surface-raised': { night: palette.deepGreenRaised, day: palette.boneRaised },
  'surface-frame': { night: palette.deepGreenFrame, day: palette.boneFrame },
  /**
   * surface-inverted genuinely flips: night -> the day base, day -> the night
   * base. It is more than a colour — `data-surface="inverted"` opens a scope in
   * which the ENTIRE token set resolves to the opposite theme, so text, muted
   * text, accent-text and borders stay legible inside it automatically.
   */
  'surface-inverted': { night: palette.bone, day: palette.deepGreen },

  // -- 4.2 Text -----------------------------------------------------------
  // `text-primary` / `text-muted` in CLAUDE.md 4.2.
  primary: { night: palette.mist, day: palette.ink },
  muted: { night: palette.mistMuted, day: palette.inkMuted },

  // -- 4.2 Accent ---------------------------------------------------------
  /** FILL ONLY. Never text, icons, thin borders or focus rings. */
  accent: { night: palette.amber, day: palette.amber },
  /** Text, icons, borders and focus rings. Resolves darker in day. */
  'accent-text': { night: palette.amber, day: palette.amberDeep },
  /** Text sitting on an `accent` fill. */
  'on-accent': { night: palette.onAmber, day: palette.onAmber },

  // -- Borders ------------------------------------------------------------
  /** Hairline / structural. Decorative, deliberately below 3:1. */
  line: { night: palette.deepGreenFrame, day: palette.boneFrame },
  /** Interactive and meaningful borders. Must clear 3:1. */
  'line-strong': { night: palette.mistMuted, day: palette.inkMuted },

  // -- Status readout (section 8) -----------------------------------------
  'status-ok': { night: palette.signalGreen, day: palette.signalGreenDeep },
  'status-warn': { night: palette.amber, day: palette.amberDeep },
  'status-down': { night: palette.signalRed, day: palette.signalRedDeep },
};

/** Single elevation treatment (one, not a ladder). */
export const shadowTokens = {
  elevated: {
    night: '0 1px 2px 0 rgb(0 0 0 / 0.45), 0 10px 30px -12px rgb(0 0 0 / 0.60)',
    day: '0 1px 2px 0 rgb(8 36 26 / 0.06), 0 10px 30px -12px rgb(8 36 26 / 0.16)',
  },
};

/**
 * Modular type scale. Base 16px, ratio 1.2 (minor third).
 * Headline steps are fluid between their own scale neighbours — never
 * arbitrary values, and never an off-scale `text-[27px]`.
 */
export const typeScale = {
  caption: '0.694rem', // 11.1px — mono tracked caps, status line (4.6 only)
  sm: '0.833rem', // 13.3px — legal strip, dense UI
  body: '1rem', // 16px
  lead: '1.2rem', // 19.2px
  h4: '1.44rem', // 23.0px
  h3: '1.728rem', // 27.6px
  h2: 'clamp(1.728rem, 1.35rem + 1.9vw, 2.074rem)', // 27.6 -> 33.2px
  h1: 'clamp(2.074rem, 1.55rem + 2.6vw, 2.986rem)', // 33.2 -> 47.8px
  display: 'clamp(2.488rem, 1.60rem + 4.4vw, 4.300rem)', // 39.8 -> 68.8px
};

/** Line heights. Headline leading tight, body leading generous (4.5). */
export const leading = {
  display: '0.98',
  heading: '1.12',
  snug: '1.35',
  body: '1.65',
};

export const tracking = {
  display: '-0.03em',
  heading: '-0.02em',
  normal: '0em',
  /** Tracked-out caps, 4.6 systems-readout layer only. */
  caps: '0.16em',
};

/** Radius scale. Hierarchy is deliberate — see report. */
export const radii = {
  xs: '2px', // mono chips, tags, status dots' housing
  sm: '4px', // buttons, inputs, small controls
  md: '10px', // cards, list rows
  lg: '20px', // full panels, the hero frame, modal sheets
  full: '9999px', // pills only
};

/** Layout rhythm. Tailwind's 0.25rem spacing ladder covers the rest. */
export const layout = {
  gutter: 'clamp(1.25rem, 4vw, 2.5rem)',
  section: 'clamp(4rem, 9vw, 7.5rem)',
  container: '1200px',
  /** Body copy caps at 72 characters (4.5). */
  measure: '72ch',
};

export const themes = ['night', 'day'];
export const defaultTheme = 'night';
